- name: Setup Vprofile bastion Host
  hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
    - name: Import VPC Setup Variable
      include_vars: vars/bastion_setup

    - name: Import VPC Setup Variable
      include_vars: vars/output_vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key,pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Sec Group for bastion hosts
      ec2_group:
        name: Bastion-host-sg
        description: Allow prot 22 from everywhre and all port within Security Group
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2_instance:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        count: 
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        security_groups: 
          - "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out